### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ScripterSaurav** [safiuddin786/SD-streams#1]
After running the code it showing
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. Please fix this

**Comment by safiuddin786** [comment]
> After running the code it showing Not Found The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. Please fix this

I have fixed API, Now its working but it might be temporary fix.
However, I will be making a new version of this API in upcoming days.
If any errors or fixes to be done, raise an issue on this repo. I will try my best to solve any issue as soon as possible.
Thank you @ScripterSaurav

**Comment by ScripterSaurav** [comment]
> I have fixed API, Now its working but it might be temporary fix. However, I will be making a new version of this API in upcoming days. If any errors or fixes to be done, raise an issue on this repo. I will try my best to solve any issue as soon as possible. Thank you @ScripterSaurav

@safiuddin786 
Thanks for updating but still it showing the same problem 😔.  If u need i have api code.

**Comment by safiuddin786** [comment]
> > I have fixed API, Now its working but it might be temporary fix. However, I will be making a new version of this API in upcoming days. If any errors or fixes to be done, raise an issue on this repo. I will try my best to solve any issue as soon as possible. Thank you @ScripterSaurav
> 
> @safiuddin786 Thanks for updating but still it showing the same problem 😔. If u need i have api code.

@ScripterSaurav API is currently working. App is currently not working, you are most welcomed to use this Api as a integration to your App (If possible add this repo as a contribution for your Application).
![Screenshot 2021-11-15 000002](https://user-images.githubusercontent.com/53482858/141693787-27d1b823-196f-45ad-88eb-8f2593f1308b.png)
